hi
Tue 21 Mar 21:12:38 GMT 2023
compute-permanent-node-746
uid=10025(asa_cooper_stickland) gid=10012(owain_evans) groups=10012(owain_evans)
/data/asa_cooper_stickland/situational-awareness
doing it in one go
1
wandb: Currently logged in as: asacoopstick. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.14.0 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.10
wandb: Run data is saved locally in /data/asa_cooper_stickland/situational-awareness/wandb/run-20230321_211249-5d14ecf8
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run asa_reawrd_test (30035_0)
wandb: ‚≠êÔ∏è View project at https://wandb.ai/asacoopstick/reward-flan-t5
wandb: üöÄ View run at https://wandb.ai/asacoopstick/reward-flan-t5/runs/5d14ecf8
Loading model
Loading tokenizer and generating datasets
Failed to generate datasets, retrying
Failed to generate datasets, retrying
Failed to generate datasets, retrying
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: üöÄ View run asa_reawrd_test (30035_0) at: https://wandb.ai/asacoopstick/reward-flan-t5/runs/5d14ecf8
wandb: Synced 6 W&B file(s), 0 media file(s), 2 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230321_211249-5d14ecf8/logs
Traceback (most recent call last):
  File "/data/asa_cooper_stickland/situational-awareness/scripts/t5/train.py", line 214, in <module>
    train(project=args.project,
  File "/data/asa_cooper_stickland/situational-awareness/scripts/t5/train.py", line 87, in train
    raise e
  File "/data/asa_cooper_stickland/situational-awareness/scripts/t5/train.py", line 78, in train
    train_dataset, eval_dataset = generate_datasets(
  File "/data/asa_cooper_stickland/situational-awareness/scripts/t5/generate_data.py", line 22, in generate_datasets
    with open(fname) as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'unrealized_examples_london.jsonl'
